version: "3.8"
services:
  db:
    image: postgres:12.1
    env_file: .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    env_file: .env
    volumes:
      - ./project:/project
    ports:
      - "3000:3000"
    depends_on:
      - db
